FROM python:3.8

LABEL maintainer="Bart Skowron <bxsx@bartskowron.com>"

RUN groupadd celery && useradd --create-home --home-dir /app -g celery celery

RUN pip install -U celery[redis] pydantic[dotenv] requests

WORKDIR /app
COPY ./.env ./
COPY ./app/celerytasks.py ./app/
COPY ./app/schemas.py ./app/

USER celery
